### ISSUE TITLE
Messaging and Study Rooms

### ISSUE THREAD

**Issue by zenzlia** [doofenshmirtz-deco-inc/OnBoard#60]
Implementing a component that will act as a way to interact with meeting rooms and instant messaging. I have no idea what else to put here so here's what we plan to get done:

# TODO:

- [x] Create basic sketch to go off of (physical sketch)
- [x] Utilise Router so that simple navigation to the messaging component is possible
- [x] Create meeting room and messaging components
- [x] Create 3 tab components within the contacts component (see below)
- [x] Be able to send messages from one user to another through the messaging component
- [x] Being able to click on a contact component will lead to the messaging page with the specific contact

## Tabs
- [x] 1. Create messaging component that allows for searching between contacts (RECENT TAB)
  - [x] Be able to create private study rooms from here 
- [x] 2. Create tab that is able to look at existing public study rooms and be able to join them (EXPLORE TAB)
- [x] 3. Create tab that is able to look at currently enrolled classes and join any open classes rooms (CLASSES TAB)
# Possible Features:
- [ ] Unicode and emoji support
- [ ] Notifications (by way of an icon change)
