### ISSUE TITLE
TODO Before Tuesday!!!!!!

### ISSUE THREAD

**Issue by sannibunny** [doofenshmirtz-deco-inc/OnBoard#96]
## Dashboard
- [x] Contacts white background thing (this should hopefully be fixed when I fix the messaging background thing)

## Calendar
- [x] Allocate+ Integration (this should populate the calendar I believe)

## My Classes
- [x] Is there any way to convert the box with the classes into a dropdown menu? (This will make sure people also know it’s clickable) -> tbh the box kinda confuses me too and I always forget I can click on the classes
- [x] Seed learning resources (a bit more than lorem ipsum but we should be good to have the same content for all courses)
- [x] Seed announcements (e.g. EDIS3801 missing announcements)
- [ ] Seed course staff (this can be quite basic)
- [x] ~~Seed ECP content (worst case -> it’s just a tab which links straight to the ECP -> no content inside the actual tab)~~
- [x] CC/tutor views (James has submitted a PR for this)

## Messaging
- [x] White background thing
- [x] Info of who’s in the group chat
- [x] Bubbles for who sent the message
- [ ] Unread messages
- [x] Log out and logging in changes bubble sides (bug fixing)
- [x] File uploads to messaging
- [ ] Seed proper groups (no lorem ipsum names)
- [ ] Inform the user when a video call has started
- [ ] A better indication of unread messages
- [ ] Possibly somewhere to collect messaging notifications
- [x] Make contacts list on the left side collapsible

## General
- [ ] Remove file uploads section from sidebar?

**Comment by TomCranitch** [comment]
yeeeeeet
